# Generated by Django 3.0.4 on 2020-03-19 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_posted']},
        ),
    ]
